---
name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install
                 pyupgrade safety
      - run: pip install --editable .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
