---
name: mypy

on: push  # yamllint disable-line rule:truthy

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install 'mypy>=0.940'
      - uses: wearerequired/lint-action@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mypy: true
          continue_on_error: false
